import os
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
LOGS_DIR = DATA_DIR / "logs"

RETRY_CONFIG = {
    "max_retries": 3,
    "retry_delay": 2,
    "backoff_factor": 2,
    "timeout": 30,
}

RATE_LIMIT = {
    "delay_seconds": 2,
    "respect_robots_txt": True,
}

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
}

CITY_MAPPING = {
    "amman": "Amman",
    "amman, jordan": "Amman",
    "zara": "Zarqa",
    "irbid": "Irbid",
    "mafraq": "Mafraq",
    "ma'an": "Ma'an",
    "aqaba": "Aqaba",
    "jadara": "Jadara",
    "tafilah": "Tafilah",
    "karak": "Karak",
    "madaba": "Madaba",
    "rushdia": "Rushdia",
    "sahab": "Sahab",
    "naour": "Naour",
    "wadi as sir": "Wadi As Sir",
}

CATEGORY_MAPPING = {
    "software development": "Software Development",
    "custom software development": "Software Development",
    "web development": "Web Development",
    "web design": "Web Development",
    "mobile app development": "Mobile App Development",
    "mobile development": "Mobile App Development",
    "ios development": "Mobile App Development",
    "android development": "Mobile App Development",
    "ecommerce development": "E-Commerce Development",
    "ecommerce": "E-Commerce Development",
    "digital marketing": "Digital Marketing",
    "online marketing": "Digital Marketing",
    "seo": "SEO",
    "search engine optimization": "SEO",
    "social media marketing": "Social Media Marketing",
    "ppc": "PPC Advertising",
    "pay per click": "PPC Advertising",
    "content marketing": "Content Marketing",
    "branding": "Branding",
    "brand strategy": "Branding",
    "ui/ux": "UI/UX Design",
    "ui design": "UI/UX Design",
    "ux design": "UI/UX Design",
    "graphic design": "Graphic Design",
    "it consulting": "IT Consulting",
    "it strategy consulting": "IT Consulting",
    "it services": "IT Services",
    "it managed services": "IT Managed Services",
    "cybersecurity": "Cybersecurity",
    "cloud": "Cloud Services",
    "cloud computing": "Cloud Services",
    "cloud consulting": "Cloud Services",
    "data analytics": "Data Analytics",
    "data science": "Data Analytics",
    "big data": "Data Analytics",
    "artificial intelligence": "AI/ML",
    "ai": "AI/ML",
    "machine learning": "AI/ML",
    "ml": "AI/ML",
    "automation": "Automation",
    "robotics": "Robotics",
    "iot": "IoT",
    "internet of things": "IoT",
    "blockchain": "Blockchain",
    "ar/vr": "AR/VR",
    "ar": "AR/VR",
    "vr": "AR/VR",
    "augmented reality": "AR/VR",
    "virtual reality": "AR/VR",
    "qa": "QA Testing",
    "testing": "QA Testing",
    "software testing": "QA Testing",
    "devops": "DevOps",
    "erp": "ERP",
    "enterprise software": "ERP",
}

IRRELEVANT_KEYWORDS = [
    "restaurant",
    "cafe",
    "pizza",
    "burger",
    "fast food",
    "grocery",
    "supermarket",
    "retail",
    "clothing",
    "fashion",
    "real estate",
    "property",
    "realty",
    "construction",
    "law firm",
    "legal",
    "medical",
    "hospital",
    "clinic",
    "dental",
    "pharmacy",
    "dentist",
    "doctor",
    "healthcare",
    "beauty salon",
    "spa",
    "gym",
    "fitness",
    "sports",
    "car repair",
    "auto",
    "mechanic",
    "plumber",
    "electrician",
]